[cli.session] # cli options
method = 'leitner'
no-color = false

[[method.leitner.boxes]]
delta_days = [1]

[[method.leitner.boxes]]
delta_days = [2, 3]

[[method.leitner.boxes]]
delta_days = [7]

[[method.leitner.boxes]]
delta_days = [14]

[[method.leitner.boxes]]
delta_days = [30]
