[content]
question_file = "question.md" # default
answer_file = "answer.md" # default
tags = ["biology", "chapter1"] # optional

[method.leitner]
box_idx = 0 # 0..=4 (5 total boxes)
next_review = { date = "2024-06-25", answer = "" }
last_review = { date = "2024-06-25", answer = "correct" }
review_history = [
    { date = "2024-06-20", answer = "correct" },
    { date = "2024-06-21", answer = "incorrect" },
    { date = "2024-06-24", answer = "correct" },
]
