[content]
question_file = "question.md" # default
answer_file = "answer.md" # default
tags = ["biology", "chapter1"] # optional

[leitner]
box = 1
next_review = { "2024-06-27": "" }
last_review = { "2024-06-25": "correct" }
review_history = [
    { "2024-06-20": "correct" },
    { "2024-06-21": "incorrect" },
    { "2024-06-24": "correct" },
]
